package model.enums;

// This class contains all the subject codes that a student could have
public enum SubjectCode {
    AANB("Applied Animal Biology"),
    ACAM("Asian Canadian and Asian Migration Studies"),
    ADHE("Adult and Higher Education"),
    AFST("African Studies"),
    AGEC("Agricultural Economics"),
    ANAT("Anatomy"),
    ANTH("Anthropology"),
    APBI("Applied Biology"),
    APPP("Applied Science Professional Program Platform"),
    APSC("Applied Science"),
    AQUA("Aquaculture"),
    ARBC("Classical Arabic"),
    ARBM("Modern Standard Arabic"),
    ARC("Alternative Routes to Computing"),
    ARCH("Architecture"),
    ARCL("Anthropological Archaeology"),
    ARST("Archival Studies"),
    ARTC("Arts Co-Op"),
    ARTH("Art History"),
    ARTS("Arts One Program"),
    ASIA("Asian Studies"),
    ASIC("Arts and Science Interdisciplinary Courses"),
    ASL("American Sign Language"),
    ASLA("Asian Languages"),
    ASTR("Astronomy"),
    ASTU("Arts Studies"),
    ATSC("Atmospheric Science"),
    AUDI("Audiology and Speech Sciences"),
    BA("Business Administration: Core"),
    BAAC("Business Administration: Accounting"),
    BABS("Business Administration: Business Statistics"),
    BAEN("Business Administration: Entrepreneurship"),
    BAFI("Business Administration: Finance"),
    BAHR("Business Administration: Human Resources Management"),
    BAIT("Business Administration: Business Technology Management"),
    BALA("Business Administration: Law"),
    BAMA("Business Administration: Marketing"),
    BAMS("Business Administration: Management Science"),
    BAPA("Business Administration: Policy Analysis"),
    BASC("Business Administration: Supply Chain"),
    BASM("Business Administration: Strategic Management"),
    BAUL("Business Administration: Urban Land Economics"),
    BEST("Forest Bioeconomy Sciences and Technology"),
    BIOC("Biochemistry"),
    BIOF("Bioinformatics"),
    BIOL("Biology"),
    BIOT("Biotechnology"),
    BMEG("Biomedical Engineering"),
    BOTA("Botany"),
    BRDG("Bridge Program"),
    BUSI("Business"),
    CAPS("Cellular, Anatomical and Physiological Sciences"),
    CCFI("Centre for Cross-Faculty Inquiry"),
    CCST("Critical and Curatorial Studies"),
    CDST("Canadian Studies"),
    CEEN("Clean Energy Engineering"),
    CELL("Cell and Developmental Biology"),
    CENS("Central, Eastern and Northern European Studies"),
    CHBE("Chemical and Biological Engineering"),
    CHEM("Chemistry"),
    CHIL("Children's Literature"),
    CHIN("Chinese"),
    CIVL("Civil Engineering"),
    CLST("Classical Studies"),
    CNPS("Counselling Psychology"),
    CNRS("Classical, Near Eastern and Religious Studies"),
    CNTO("Cantonese"),
    COEC("Commerce Economics"),
    COGS("Cognitive Systems Program"),
    COHR("Commerce Human Resources"),
    COLX("Computational Linguistics"),
    COMM("Commerce"),
    COMR("Commerce Minor"),
    CONS("Natural Resources Conservation"),
    CPEN("Computer Engineering"),
    CPSC("Computer Science"),
    CRWR("Creative Writing"),
    CSIS("Critical Studies in Sexuality"),
    CSPW("Coordinated Science Program Workshop"),
    CTLN("Catalan"),
    DANI("Danish"),
    DENT("Dentistry"),
    DES("Design"),
    DHYG("Dental Hygiene"),
    DMED("Digital Media"),
    DSCI("Data Science"),
    ECED("Early Childhood Education"),
    ECON("Economics"),
    ECPS("Educational & Counselling Psychology, & Special Education"),
    EDCP("Curriculum and Pedagogy"),
    EDST("Educational Studies"),
    EDUC("Education"),
    EECE("Electrical and Computer Engineering"),
    ELEC("Electrical Engineering"),
    ELI("English Language Institute"),
    EMBA("Executive M.B.A."),
    ENDS("Environmental Design"),
    ENGL("English"),
    ENPH("Engineering Physics"),
    ENPP("Engineering and Public Policy"),
    ENVE("Environmental Engineering"),
    ENVR("Environmental Science"),
    EOSC("Earth and Ocean Sciences"),
    EPSE("Educational Psychology and Special Education"),
    ETEC("Educational Technology"),
    EXCH("Exchange Programs"),
    EXGR("Exchange Graduate Research"),
    FACT("Faculty of Arts Commuter Transition Program"),
    FCOR("Forestry Core"),
    FEBC("Forest Engineering British Columbia"),
    FHIS("French, Hispanic and Italian Studies"),
    FRE("Food and Resource Economics"),
    FREN("French"),
    FRSI("Forestry Silviculture Institute"),
    FRST("Forestry"),
    FSCT("Biochemistry and Forensic Science"),
    GBPR("Green Bioproducts"),
    GEM("Geomatics for Environmental Management"),
    GENE("Genetics"),
    GEOB("Geographical Sciences"),
    GEOG("Geography"),
    GEOS("Geographical Sciences"),
    GERM("German"),
    GREK("Greek"),
    GRS("Global Resource Systems"),
    GRSJ("Gender, Race, Sexuality and Social Justice"),
    GSAT("Genome Science and Technology"),
    HEBR("Hebrew"),
    HESO("Health and Society"),
    HGSE("Haida Gwaii Semesters"),
    HINU("Hindi-Urdu"),
    HIST("History"),
    HPB("High Performance Buildings"),
    HUNU("Human Nutrition"),
    IAR("Institute of Asian Research"),
    IEST("European Studies"),
    IGEN("Integrated Engineering"),
    ILS("Indigenous Land Stewardship"),
    INDO("Indonesian"),
    INDS("Interdisciplinary Studies"),
    INFO("Information Studies"),
    INLB("Indigenous Land-Based Studies"),
    ISCI("Integrated Sciences"),
    ITAL("Italian"),
    ITST("Italian Studies"),
    IWME("Integrated Water Management Engineering"),
    JAPN("Japanese"),
    JRNL("Journalism"),
    KIN("Kinesiology"),
    KORN("Korean"),
    LAIS("Library, Archival and Information Studies"),
    LASO("Law and Society"),
    LAST("Latin American Studies"),
    LATN("Latin"),
    LAW("Law"),
    LFS("Land & Food Systems"),
    LIBE("Teacher Librarianship"),
    LIBR("Library and Information Studies"),
    LING("Linguistics"),
    LLED("Language and Literacy Education"),
    LWS("Land and Water Systems"),
    MANU("Manufacturing Engineering"),
    MATH("Mathematics"),
    MTRL("Materials Engineering"),
    MUSC("Music"),
    NAME("Naval Architecture and Marine Engineering"),
    NEPL("Nepali"),
    NEST("Near Eastern Studies"),
    NEUR("Neurosurgery"),
    NRSC("Neuroscience Graduate"),
    NSCI("Neuroscience Undergraduate"),
    ORPA("Orthopaedics"),
    OSOT("Occupational Science and Occupational Therapy"),
    PATH("Pathology"),
    PCTH("Pharmacology and Therapeutics"),
    PERS("Persian"),
    PHAR("Pharmaceutical Sciences"),
    PHIL("Philosophy"),
    PHRM("Pharmacy"),
    PHTH("Physical Therapy"),
    PHYL("Cellular and Physiological Sciences"),
    PHYS("Physics"),
    PLAN("Community and Regional Planning"),
    PLAS("Plastic Surgery"),
    PLNT("Plant Science"),
    POLI("Political Science"),
    POLS("Polish"),
    PORT("Portuguese"),
    PPGA("Public Policy and Global Affairs"),
    PRHC("Primary Health Care"),
    PSYC("Psychology"),
    RADI("Radiology"),
    RUSS("Russian"),
    SANS("Sanskrit"),
    SCAN("Scandinavian"),
    SCIE("Science"),
    SEAL("Southeast Asian Languages"),
    SGES("Smart Grid Energy Systems"),
    SLAV("Slavic Studies"),
    SOAL("South Asian Languages"),
    SOCI("Sociology"),
    SOIL("Soil Science"),
    SOWK("Social Work"),
    SPAN("Spanish"),
    SPE("Sustainable Process Engineering"),
    STAT("Statistics"),
    STS("Science and Technology Studies"),
    SURG("Surgery"),
    SWED("Swedish");

    public final String title;

    SubjectCode(String subjectTitle) {
        this.title = subjectTitle;
    }

    public static SubjectCode getEnum(String value) {
        for (SubjectCode s: values()) {
            if (s.toString().equalsIgnoreCase(value)) {
                return s;
            }
        }
        return null;
    }

    @Override
    public String toString() {
        return title;
    }
}
